version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/r00t_r3b3lz
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - uploads:/app/public/uploads
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_DATABASE=r00t_r3b3lz
    restart: unless-stopped

volumes:
  mongodb_data:
  uploads:
